### ISSUE TITLE
Go through all issues in Swashbuckle

### ISSUE THREAD

**Issue by Havunen** [Havunen/DotSwashbuckle2#3]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2766

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2765 seems weird use-case one could add another layer of indirection (ie. singleton pattern to fix it at the application level)

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2764 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2761 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2759 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2758 🚧

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2757 🟡 skip, it is swagger UI bug

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2756 🆗 (3.0.2)

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2755 🟡 user error

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2753 🟡 answered

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2752 ❓ - waiting

**Comment by Havunen** [comment]
https://github.com/Havunen/DotSwashbuckle/issues/3 🟡  answered

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2749 ❓ - unclear, needs more info

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2747 🟡 answered

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2748 ❓ - unclear, needs more info

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2745 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2744 :ok

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2743 👍 good feature request, will implement

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2741 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2740 https://github.com/dotnet/aspnetcore/issues/52380 👍  good feature request, will implement // PR welcome

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2737 🟡 answered, might be fixed already

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2733 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2732 🆗 answered

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2731 🆗 (3.0.2)

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2729 🐛 bug, needs repro

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2728 🟡 I don't know. it feels non-standard feature

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2725 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2722 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2721 🟡 ui stuff, check later

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2717 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2716 ❓ unclear, needs more info

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2712 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2709 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2708 ❓ unclear, what is the problem

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2707 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2706 🆗 this project supports .NET 8 and later only

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2702 🆗 seems to be ok.

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2701 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2700 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2698 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2696 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2691 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2689 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2688 🆗

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2686 🆗 (will be fixed in 3.0.3)

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2684 🟡 answered,

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2681 🆗  old version not supported

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2680 🆗 should work

**Comment by vdekercd** [comment]
I see that the code in my PR for https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2697 is in this repo.
[domaindrivendev/Swashbuckle.AspNetCore#2628](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2628) 🆗 Should work too.

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2679 :ok (3.0.3+)

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2678 ❓ unclear, asked for more info

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2673 👍 seems to be solved

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2669 🟡 work-around available

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2668 🟡 skip, unless there is wider demand for this feature

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2667 🟡 skip

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2666 🟡 nice to have

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2665 🟡 requires Microsoft to change dependency or use custom setup

**Comment by Havunen** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2664 🆗 seems to be solved already

**Comment by worming004** [comment]
Hello @Havunen,

Thx for the initiative of this repository. This is not an easy task, and hoping for you the best.

I see that you are rewriting commit history with your own name. I am sure it is a convenient way to achieve the merge process.
I have unfortunately to warn of the consequences of rewriting commit history. There is 2 big issue by doing it.

First, it is removing authorship trace. It means you apply your name on changes made by other people. It look trivial, but it matters a lot.
The code is in MIT, if everyone would play the game, each contributour would have to add it's name to the license header or licence file. That the correct legal way to put MIT licence on contributor code.
But it is somehow implicitely agreed that a PR is submitting accor to push *personnal code* under the original licence selected by maintener. MIT in this case. The MIT agreement made by contributor is now implicitely linked with author name.
By putting your name on commits, it's like your are attributing authorship on code that you didn't write. You could face legal issues.

Second, you are preventing community driven work. I knew another opensource project where maintener was acting like this *regularly*. Unfortunately, I do not find back the other opensource golang project as example. The maintener by several time reworked history, and putted it's name into commits. Removing *visibility* of contributors.
The consequences was bad reputation, no more contributors showed up, and project was relying only on investment of the main maintener. I remind redditors of golang very upset of their name removed from their effort. I do not know what is the current state of this project as I do not find back.

So, I do not want to blame what is a hard work you are doing. I just want to ensure you know the consequences and risks that changing commit author is armfull in point of view of legal, and reputation.
I do not want neither to blame nor make you intro trouble. That the opposite. I'm pretty sure you are doing this hard job with naive knowledge of implications. It is important that you know what are the implication of the current selected method.

Hoping that help you

**Comment by Havunen** [comment]
> First, it is removing authorship trace. It means you apply your name on changes made by other people. It look trivial, but it matters a lot.

Are you referring to the source control history?

> The code is in MIT, if everyone would play the game, each contributour would have to add it's name to the license header or licence file. That the correct legal way to put MIT licence on contributor code.

That would be perfectly fine to me, I just need a working piece of software

> But it is somehow implicitely agreed that a PR is submitting accor to push personnal code under the original licence selected by maintener. MIT in this case. The MIT agreement made by contributor is now implicitely linked with author name.
By putting your name on commits, it's like your are attributing authorship on code that you didn't write. You could face legal issues.

Yeah the information gets sort of lost, that is why I tried to link all the original PRs with the commit messages. Also not all of them were ported as is, I had to do changes due differences in this fork

**Comment by worming004** [comment]
Yes, I am referencing the commit history.

> That would be perfectly fine to me, I just need a working piece of software
If you just want a personnal copy of your own usage or company, it **should** be fine (but I would not put my life on it). You can ignore my message, and should probably put this repository in private to remove any misrepresentation of commit owership. (Still, would ask a lawyer, I am not 100% sure that it is permitted)

About the MIT licence, it say what you can do from a copy of code someone else give to the community. As the licence say, it  permit multiple kind of **usages** and it is very permissive.

But it doesn't allow changing authorship in any way. Having the permission and getting ownership are 2 distincts matters.

For example, if I make a statue for public place in my city, I can permit the city to place it with equivalent if MIT license, do whatever they wants to, clean, destroy, putting funny wearings, replace head by a pumpkin. I gave permission, and they use as they wants.
But they never can claim they make the status with another creator. The authorship is my. And I know no way to change recognized authorship of a piece of creation.
It is the same for code creation. You are legally and welcome to use any contribution under MIT licence for your project/product. But in any case, you cannot claim being author of it.

**Maybe** adding a note somewhere in the repo saying **explicitely** that commit author in this repo doesn't reflect authorship. It would remove the misrepresentation that this discussion is about. But I would 100% check with a layer if it's still legal.

---

In the meantime, I see you already took action to make it properly in another repository. I am pretty sure people will love that you take effort to preserve names of contributors <3 It's important for them. It's not just a legal matter :)

**Comment by Havunen** [comment]
> I am pretty sure people will love that you take effort to preserve names of contributors <3 It's important for them 

perfect, lets continue there ❤️ 

It will take some time for me to move everything over

**Comment by Havunen** [comment]
Closing this issue in favor of: https://github.com/Havunen/DotSwashbuckle/issues/3
